# Generated by Django 6.0.2 on 2026-02-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standings',
            name='goal_diff',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='team_name',
        ),
        migrations.AddField(
            model_name='standings',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teams'),
        ),
    ]
