# Generated by Django 6.0.2 on 2026-02-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_standings_goal_diff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topscorer',
            name='team',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('match_status', models.TextField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='stats.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Goal', 'Goal'), ('Assist', 'Assist'), ('Yellow Card', 'Yellow Card'), ('Red Card', 'Red Card'), ('Own Goal', 'Own Goal')], default='Goal', max_length=50)),
                ('minute', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Standings',
        ),
        migrations.DeleteModel(
            name='TopScorer',
        ),
    ]
