# Generated by Django 6.0.2 on 2026-03-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_match_away_score_match_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_in_premier_league',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('SCHEDULED', 'Scheduled'), ('IN_PLAY', 'Live')], default='FINISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.team'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('ASSIST', 'Assist'), ('YELLOW', 'Yellow Card'), ('RED', 'Red Card'), ('OWN_GOAL', 'Own Goal'), ('SUB', 'Substitution'), ('PENALTY', 'Penalty')], default='GOAL', max_length=20)),
                ('minute', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_events', to='stats.player')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_match_events', to='stats.player')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.DeleteModel(
            name='MatchEvents',
        ),
    ]
