# Generated by Django 6.0.2 on 2026-03-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_remove_player_age_player_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team')},
        ),
    ]
