# Generated by Django 6.0.2 on 2026-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_team_logo_alter_match_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
