# Generated by Django 6.0.2 on 2026-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_player_assists_player_goals_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
