# Generated by Django 6.0.2 on 2026-04-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_team_draws_team_goals_against_team_goals_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
