# Generated by Django 6.0.2 on 2026-04-23 21:14

import django
from django.db import migrations

def populate_stats(apps, schema_editor):
    # Use apps.get_model to get the historical version of the model
    Team = apps.get_model('stats', 'Team')
    Match = apps.get_model('stats', 'Match')

    for team in Team.objects.all():
        # Filter matches for this team that are FINISHED
        # Note: We manually calculate here because we can't easily 
        # import your 'get_stats' method into a migration safely.
        matches = Match.objects.filter(match_status='FINISHED').filter(
            django.db.models.Q(home_team=team) | django.db.models.Q(away_team=team)
        )
        
        points = 0
        played = 0
        wins = 0
        draws = 0
        losses = 0
        gf = 0
        ga = 0

        for m in matches:
            played += 1
            if m.home_team == team:
                gf += m.home_score
                ga += m.away_score
                if m.home_score > m.away_score: wins += 1; points += 3
                elif m.home_score < m.away_score: losses += 1
                else: draws += 1; points += 1
            else:
                gf += m.away_score
                ga += m.home_score
                if m.away_score > m.home_score: wins += 1; points += 3
                elif m.away_score < m.home_score: losses += 1
                else: draws += 1; points += 1
        
        team.points = points
        team.played = played
        team.wins = wins
        team.draws = draws
        team.losses = losses
        team.goals_for = gf
        team.goals_against = ga
        team.goal_difference = gf - ga
        team.save()

class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0012_team_goal_difference_team_points'),
    ]

    operations = [
        migrations.RunPython(populate_stats),
    ]