# Generated by Django 6.0.2 on 2026-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_populate_team_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'LIVE')], default='SCHEDULED', max_length=20),
        ),
    ]
