# Generated by Django 6.0.2 on 2026-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_team_instagram_handle_team_twitter_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
